---
title: "Empirical bias reducing methods for Structural Equation Models"
format: gfm
execute: 
  echo: false
  warning: false
---

```{r}
#| label: setup
#| include: false
library(tidyverse)
library(lavaan)
library(semPlot)
```


Last modified: `r Sys.Date()`

## Normal CFA toy example

```{r}
#| label: fig-toyexample
#| echo: true
# Simulate data
mod <- "fx =~ 1*x1 + 0.8*x2 + 0.6*x3"
n   <- 200
dat <- simulateData(model = mod, sample.nobs = n)
fit <- cfa(model = "fx =~ x1 + x2 + x3", data = dat)
semPaths(fit, "est", rotation = 3)
```

Average bias across `B=1000` simulations (sample size n = 200):

```{r}
#| echo: false
load("R/factor_models/sims_toyexample.RData")
do.call(rbind, res) |>
  # mutate(across(c(ml, ebrm, jack, boot), \(x) as.vector(x - truth))) |>
  # pivot_longer(
  #   cols = c(ml, ebrm, jack, boot),
  #   names_to = "method",
  # ) |>
  # ggplot(aes(value, par, fill = method)) +
  # geom_boxplot(coef = Inf)
  summarise(
    across(c(ml, ebrm, jack, boot), \(x) mean(x - truth, na.rm = TRUE)),
    .by = par
  )
```

## Growth curve models

### Convergence failures and timings

```{r}
#| label: tab-bootfail-growth
load("R/factor_models/summary_growth_sim.RData")
options(knitr.kable.NA = "")
tab_time_fail_growth |>
  mutate(across(starts_with("fail"), \(x) {
    out <- x
    out[x == 0] <- NA
    out
  })) |>
  mutate(
    across(starts_with("fail"), \(x) scales::percent(x, accuracy = 0.01)),
    across(starts_with("time"), gt::vec_fmt_duration)
  ) |>
  kableExtra::kbl(format = "pipe")
```

### Relative median bias plot

```{r}
#| label: fig-bias-growth
#| fig-dpi: 300
#| out-width: 100%
p_med_bias_growth
```


## Two factor SEM

TBC

