project:
  type: manuscript
  output-dir: ../docs/manuscript

manuscript:
  article: index.qmd

notebook-links: false

format:
  html:
    number-sections: true
    other-links:
      - text: PRELIM RESULTS
        icon: database      
        href: results.html       
  # docx:
  #   output-file: jamil2025bias
  tandf-pdf:
    link-citations: true
    keep-tex: true
    linenumbers: true
    fig-width: 7
    fig-height: 5
    fig-pos: 'htbp'
    header-includes:
      # - \input{maths_shortcuts.tex}
      - \usepackage{setspace}
      - \onehalfspacing
      # - \usepackage{afterpage}
      # - \newcommand{\blscape}{\begin{landscape}}
      # - \newcommand{\elscape}{\end{landscape}}
    output-file: jamil2025bias

execute:
  freeze: auto
  cache: false
  echo: false

bibliography: 
  - refs-HJ.bib
  - refs-OK.bib

# csl: apa.csl

citation:
  type: article-journal
  # container-title: "Journal of Data Science Software"
  # doi: "10.23915/reprodocs.00010"
  # url: https://example.com/summarizing-output
google-scholar: true
