project:
  type: manuscript
  output-dir: ../docs/manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx:
    output-file: jamil2024bias
  tandf-pdf:
    link-citations: true
    keep-tex: true
    linenumbers: true
    fig-width: 7
    fig-height: 5
    fig-pos: 'htbp'
    header-includes:
      # - \input{maths_shortcuts.tex}
      - \usepackage{setspace}
      - \onehalfspacing
      # - \usepackage{afterpage}
      # - \newcommand{\blscape}{\begin{landscape}}
      # - \newcommand{\elscape}{\end{landscape}}
    output-file: jamil2024bias

execute:
  freeze: true

notebook-links: false


