---
title: Bias-Reduced Estimation of Structural Equation Models
authors:
  - name: Haziq Jamil
    orcid: 0000-0003-3298-1010
    email: haziq.jamil@ubd.edu.bn
    url: "https://haziqj.ml"
    # note: 
    # roles: writing
    corresponding: true
    affiliations:
      - name: Universiti Brunei Darussalam
        id: ubd
        department: Mathematical Sciences, Faculty of Science
        address: Universiti Brunei Darussalam, Jalan Tungku Link
        city: Bandar Seri Begawan
        country: Brunei
        postal-code: BE 1410
      - name: London School of Economics and Political Science
        id: lse
        department: Department of Statistics
        address: Columbia House, Houghton Street
        city: London
        country: United Kingdom
        postal-code: WC2A 2AE
    attributes:
      corresponding: true
  - name: Yves Rosseel
    orcid: 0000-0002-4129-4477
    email: Yves.Rosseel@UGent.be
    affiliations:
      - name: Ghent University
        id: ugent
        department: Center for Data Analysis and Statistical Science
        address: Krijgslaan 281 - S9
        city: Gent
        country: Belgium
        postal-code: 9000
  - name: Oliver Kemp
    # orcid: 
    email: Oliver.Kemp@warwick.ac.uk
    affiliations:
      - name: University of Warwick
        id: warwick
        department: Department of Statistics
        address: Zeeman Building, University of Warwick
        city: Coventry
        country: United Kingdom
        postal-code: CV4 7AL
  - name: Ioannis Kosmidis
    email: ioannis.kosmidis@warwick.ac.uk
    orcid: 0000-0003-1556-0302
    affiliations:
      - id: warwick
bibliography: 
  - refs-HJ.bib
csl: apa.csl
nocite: |
  @*
abstract: |
  Abstract here.
---

```{r}
#| label: setup
#| include: false
library(tidyverse)
theme_set(theme_bw())
library(gt)
load(here::here("../experiments/tables_figures.RData"))
```

```{r}
#| label: tbl-tab1
#| tbl-cap: 'Convergence failure counts for the ML and Bias-reduced estimators (maximum = 1000).'
tab1
```

## Growth Curve Model

```{r}
#| label: tbl-tab2
#| tbl-cap: 'Results (trimmed) growth curve model reliability .80.'
tab2 
```

```{r}
#| label: tbl-tab3
#| tbl-cap: 'Results (trimmed) growth curve model reliability .50.'
tab3
```

```{r}
#| label: fig-fig3
#| fig-cap: 'Relative median bias (model a).'
fig3
```

```{r}
#| label: fig-fig4
#| fig-cap: 'Relative mean bias (model a).'
fig4
```


```{r}
#| label: fig-fig5
#| fig-cap: 'Root mean square error (RMSE) of bias-corrected estimators relative to the Maximum Likelihood baseline (model a).'
fig5
```

```{r}
#| label: tbl-tab4
#| tbl-cap: 'Coverage rates 95% confidence intervals (model a).'
tab4
```

## Two-factor Model

```{r}
#| label: tbl-tab5
#| tbl-cap: 'Results (trimmed) two-factor model reliability .80.'
tab5
```

```{r}
#| label: tbl-tab6
#| tbl-cap: 'Results (trimmed) two-factor model reliability .50.'
tab6
```

```{r}
#| label: fig-fig6
#| fig-cap: 'Relative median bias (model b).'
fig6
```

```{r}
#| label: fig-fig7
#| fig-cap: 'Relative mean bias (model b).'
fig7
```

```{r}
#| label: fig-fig8
#| fig-cap: 'Root mean square error (RMSE) of bias-corrected estimators relative to the Maximum Likelihood baseline (model b).'
fig8
```

```{r}
#| label: tbl-tab7
#| tbl-cap: 'Coverage rates 95% confidence intervals (model b).'
tab7
```


## References

