---
title: Simulation results
author: Haziq Jamil
grid:
  sidebar-width: 0px
---

```{r}
#| label: setup
#| include: false
library(tidyverse)
theme_set(theme_bw())
library(gt)
load(here::here("notebooks/tables_figures.RData"))

my_render_tab <- function(x) {
  if (knitr::is_html_output()) {
    x
  } else if (knitr::is_latex_output()) {
    as_latex(x)
  } else {
    NULL
  }     
}
```

```{r}
#| label: tbl-tab1
#| tbl-cap: 'Convergence failure counts for the ML and Bias-reduced estimators (maximum = 1000).'
my_render_tab(tab1)
```

## Growth Curve Model

```{r}
#| label: tbl-tab2
#| tbl-cap: 'Results (trimmed) growth curve model reliability .80.'
my_render_tab(tab2)
```

```{r}
#| label: tbl-tab3
#| tbl-cap: 'Results (trimmed) growth curve model reliability .50.'
my_render_tab(tab3)
```

```{r}
#| label: fig-fig3
#| fig-cap: 'Relative median bias (model a).'
fig3
```

```{r}
#| label: fig-fig4
#| fig-cap: 'Relative mean bias (model a).'
fig4
```


```{r}
#| label: fig-fig5
#| fig-cap: 'Root mean square error (RMSE) of bias-corrected estimators relative to the Maximum Likelihood baseline (model a).'
fig5
```

```{r}
#| label: tbl-tab4
#| tbl-cap: 'Coverage rates 95% confidence intervals (model a).'
my_render_tab(tab4)
```

## Two-factor Model

```{r}
#| label: tbl-tab5
#| tbl-cap: 'Results (trimmed) two-factor model reliability .80.'
my_render_tab(tab5)
```

```{r}
#| label: tbl-tab6
#| tbl-cap: 'Results (trimmed) two-factor model reliability .50.'
my_render_tab(tab6)
```

```{r}
#| label: fig-fig6
#| fig-cap: 'Relative median bias (model b).'
fig6
```

```{r}
#| label: fig-fig7
#| fig-cap: 'Relative mean bias (model b).'
fig7
```

```{r}
#| label: fig-fig8
#| fig-cap: 'Root mean square error (RMSE) of bias-corrected estimators relative to the Maximum Likelihood baseline (model b).'
fig8
```

```{r}
#| label: tbl-tab7
#| tbl-cap: 'Coverage rates 95% confidence intervals (model b).'
my_render_tab(tab7)
```
