project:
  type: manuscript
  output-dir: ../../docs/manuscript/brsem

manuscript:
  article: sem-bias.qmd

notebook-links: false

format:
  html:
    number-sections: true
    fontsize: 110%
    lightbox: true
    # page-layout: full
    grid:
      sidebar-width: 200px
      body-width: 900px
      margin-width: 0px
    include-in-header:
      # https://github.com/quarto-dev/quarto-cli/discussions/9248
      text: |
        <style>
          span.math.display {
            display: block;
            overflow-x: auto;
            overflow-y: hidden;
            white-space: nowrap;  /* optional: prevents math from wrapping */
          }
        </style>

  tandf-pdf:
    wrap: preserve
    link-citations: true
    keep-tex: true
    linenumbers: true
    fig-width: 7
    fig-height: 5
    fig-pos: 'htbp'
    header-includes:
      # - \input{maths_shortcuts.tex}
      - \usepackage{setspace}
      - \onehalfspacing
    output-file: jamil2025bias
    cite-method: biblatex

execute:
  freeze: auto
  cache: true
  echo: false

bibliography:
  - ../refs-HJ.bib
  - ../refs-OK.bib

csl: ../apa.csl

citation:
  type: article-journal
  container-title: 'Manuscript in preparation'
  # doi: "10.23915/reprodocs.00010"
  url: https://haziqj.ml/sem-bias/brsem
google-scholar: true

filters:
  - highlight-text
