---
title: Bias-Reduced Estimation of Structural Equation Models
authors:
  - name: Haziq Jamil
    orcid: 0000-0003-3298-1010
    email: haziq.jamil@ubd.edu.bn
    # corresponding: true
    url: "https://haziqj.ml"
    affiliations:
      - name: Universiti Brunei Darussalam
        id: ubd
        department: Mathematical Sciences, Faculty of Science
        address: Universiti Brunei Darussalam, Jalan Tungku Link
        city: Bandar Seri Begawan
        country: Brunei
        postal-code: BE 1410
      - name: London School of Economics and Political Science
        id: lse
        department: Department of Statistics
        address: Columbia House, Houghton Street
        city: London
        country: United Kingdom
        postal-code: WC2A 2AE
  - name: Yves Rosseel
    orcid: 0000-0002-4129-4477
    email: Yves.Rosseel@UGent.be
    affiliations:
      - name: Ghent University
        id: ugent
        department: Department of data analysis
        address: Henri Dunantlaan 2
        city: Gent
        country: Belgium
        postal-code: 9000
  - name: Oliver Kemp
    # orcid: 
    email: Oliver.Kemp@warwick.ac.uk
    affiliations:
      - name: University of Warwick
        id: warwick
        department: Department of Statistics
        address: Mathematical Sciences Building, University of Warwick
        city: Coventry
        country: United Kingdom
        postal-code: CV4 7AL
  - name: Ioannis Kosmidis
    email: ioannis.kosmidis@warwick.ac.uk
    orcid: 0000-0003-1556-0302
    affiliations:
      - ref: warwick
date-modified: last-modified
abstract: |
  An exploration of explicit and implicit bias-reduced maximum likelihood estimation for structural equation models (SEMs) and latent growth curve models (LGCMs) is presented. Comparisons to prior work on resampling-based methods like Bootstrap and Jackknife are made. Performance of our methods are favourable.
keywords:
  - Structural Equation Models
  - Growth Curve Models
  - Bias Reduction
filters:
  - highlight-text
---


```{r}
#| label: setup
#| include: false
library(tidyverse)
library(brlavaan)
library(gt)
library(glue)
library(semPlot)
library(semptools)
load("results.RData")
```


## Introduction

{{< include _intro.qmd >}}

[To place this table elsewhere (or remove)]{bg-colour="#FFEA00"}


```{r}
#| label: tbl-timing
#| tbl-cap: 'Comparison of mean computation times (in seconds, with standard deviations in parentheses) for estimating the two-factor SEM and latent growth curve models for $n=1000$.'
#| html-table-processing: none
res_timing_n1000 |>
  rowwise() |>
  mutate(
    thing = glue::glue("{gt::vec_fmt_number(mean)} ({gt::vec_fmt_number(sd)})"),
    method = factor(
      method,
      levels = c("ML", "lav", "eRBM", "iRBM", "JB", "BB", "Ozenne", "REML"),
      labels = names(mycols)
    )
  ) |>
  select(-mean, -sd) |>
  pivot_wider(names_from = model, values_from = thing) |>
  arrange(method) |>
  gt() |>
  sub_missing(missing_text = "") |>
  cols_label(
    method = "Method",
    twofac = "Two-factor SEM",
    growth = "Latent growth curve model"
  ) |>
  cols_width(
    twofac ~ px(180),
    growth ~ px(180)
  )
```

## Methodology

{{< include _method.qmd >}}

## Simulation Study

{{< include _simulation.qmd >}}

## Results

{{< include _results.qmd >}}

## Discussion

{{< include _discussion.qmd >}}

## References {.unnumbered}

::: {#refs}
:::

## Appendix {.unnumbered}

{{< include _appendix.qmd >}}



