#' Generate data for simulation studies
#'
#' Generate data for simulation studies.
#'
#' The function `truth()` is a simple extractor function to retrieve the true
#' values of the data set generated by `gen_data_growth()` or
#' `gen_data_twofac()`.
#'
#' @param n Sample size
#' @param rel Reliability of the growth curve model. Either 0.8 or 0.5.
#' @param dist Distribution of the manifest variables. Either "Normal",
#'   "Kurtosis" or "Non-normal".
#' @param lavsim Logical. If TRUE, simulate data using lavaan's [simulateData]
#'   function.
#' @param meanstructure Logical (this is almost always `FALSE`). If `TRUE`,
#'   include the mean structure in the estimation. Only for two-factor models
#'   (since growth models do not have a mean structure).
#' @param seed Seed for reproducibility.
#' @param scale Scaling factor for the data. Default is 1, but for the growth
#'   curve model data, it is found that having a smaller scale (1/10) can be
#'   beneficial for convergence.
#'
#' @return A data frame with simulated data. For convenience, both the true
#'   values (`"truth"`) and distribution (`"dist"`) are attached as attributes.
#' @name gen-data
#'
#' @author Original code by Sara Dhaene and Yves Rosseel.
#' @references Dhaene, S., & Rosseel, Y. (2022). Resampling Based Bias
#'   Correction for Small Sample SEM. *Structural Equation Modeling: A
#'   Multidisciplinary Journal, 29*(5), 755–771.
#'   https://doi.org/10.1080/10705511.2022.2057999
#'
#' @examples
#' dat <- gen_data_growth(n = 100, rel = 0.8)
#' head(dat)
#' truth(dat)
NULL

#' Model specification for latent growth curve models
#' @inherit gen-data params
#' @return A character string with the model specification, used for either
#'   fitting lavaan models or simulating data.
#' @name growth-curve
#' @examples
#' txt_mod_growth_pop(0.8)
#' txt_mod_growth(0.5)
NULL

#' Model specification for two-factor SEM models
#' @inherit gen-data params
#' @inherit growth-curve return
#' @name two-fac
NULL

#' Retrieve the true values of the models used for simulation
#' @inherit gen-data params
#' @return A named numeric vector with the true values of the model.
#' @name true-values
#' @examples
#' truth_growth(0.8)
#' truth_twofac(0.5)
NULL

## ----- Growth curve models (model a) -----------------------------------------
#' @rdname growth-curve
#' @export
txt_mod_growth_pop <- function(rel) {
  if (rel == "0.8") {
    # Mean reliability 0.80 ----------------------------------------------------
    mod <- "
    # intercept with coefficients fixed to 1
    i =~  1*Day0 + 1*Day1 + 1*Day2 + 1*Day3 + 1*Day4 +
          1*Day5 + 1*Day6 + 1*Day7 + 1*Day8 + 1*Day9

    # slope with coefficients fixed to 0:9 (number of days)
    s =~  0*Day0 + 1*Day1 + 2*Day2 + 3*Day3 + 4*Day4 +
          5*Day5 + 6*Day6 + 7*Day7 + 8*Day8 + 9*Day9

    i ~~ 550*i
    i ~ 0*1

    s ~~ 100*s
    s ~ 0*1

    i ~~ 40*s

    Day0 ~~ 500*Day0
    Day1 ~~ 500*Day1
    Day2 ~~ 500*Day2
    Day3 ~~ 500*Day3
    Day4 ~~ 500*Day4
    Day5 ~~ 500*Day5
    Day6 ~~ 500*Day6
    Day7 ~~ 500*Day7
    Day8 ~~ 500*Day8
    Day9 ~~ 500*Day9
    "
  }
  if (rel == "0.5") {
    # Mean reliability 0.50 ----------------------------------------------------
    mod <- "
    # intercept with coefficients fixed to 1
    i =~  1*Day0 + 1*Day1 + 1*Day2 + 1*Day3 + 1*Day4 +
          1*Day5 + 1*Day6 + 1*Day7 + 1*Day8 + 1*Day9

    # slope with coefficients fixed to 0:9 (number of days)
    s =~  0*Day0 + 1*Day1 + 2*Day2 + 3*Day3 + 4*Day4 +
          5*Day5 + 6*Day6 + 7*Day7 + 8*Day8 + 9*Day9

    i ~~ 275*i
    i ~ 0*1

    s ~~ 50*s
    s ~ 0*1

    i ~~ 20*s

    Day0 ~~ 1300*Day0
    Day1 ~~ 1300*Day1
    Day2 ~~ 1300*Day2
    Day3 ~~ 1300*Day3
    Day4 ~~ 1300*Day4
    Day5 ~~ 1300*Day5
    Day6 ~~ 1300*Day6
    Day7 ~~ 1300*Day7
    Day8 ~~ 1300*Day8
    Day9 ~~ 1300*Day9
    "
  }

  mod
}

#' @rdname growth-curve
#' @export
txt_mod_growth <- function(rel) {
  "
  # intercept with coefficients fixed to 1
  i =~  1*Day0 + 1*Day1 + 1*Day2 + 1*Day3 + 1*Day4 +
        1*Day5 + 1*Day6 + 1*Day7 + 1*Day8 + 1*Day9

  # slope with coefficients fixed to 0:9 (number of days)
  s =~  0*Day0 + 1*Day1 + 2*Day2 + 3*Day3 + 4*Day4 +
        5*Day5 + 6*Day6 + 7*Day7 + 8*Day8 + 9*Day9

  i ~~ i
  i ~ 1

  s ~~ s
  s ~ 1

  i ~~ s

  # fix intercepts
  Day0 ~ 0*1
  Day1 ~ 0*1
  Day2 ~ 0*1
  Day3 ~ 0*1
  Day4 ~ 0*1
  Day5 ~ 0*1
  Day6 ~ 0*1
  Day7 ~ 0*1
  Day8 ~ 0*1
  Day9 ~ 0*1

  # apply equality constraints
  Day0 ~~ v*Day0
  Day1 ~~ v*Day1
  Day2 ~~ v*Day2
  Day3 ~~ v*Day3
  Day4 ~~ v*Day4
  Day5 ~~ v*Day5
  Day6 ~~ v*Day6
  Day7 ~~ v*Day7
  Day8 ~~ v*Day8
  Day9 ~~ v*Day9
  "
}

# txt_mod_growth <- function(rel) {
#   rel <- match.arg(as.character(rel), c("0.8", "0.5"))
#
#   if (rel == "0.8") {
#     mod <- "
#       # intercept with coefficients fixed to 1
#       i =~  1*Day0 + 1*Day1 + 1*Day2 + 1*Day3 + 1*Day4 +
#             1*Day5 + 1*Day6 + 1*Day7 + 1*Day8 + 1*Day9
#
#       # slope with coefficients fixed to 0:9 (number of days)
#       s =~  0*Day0 + 1*Day1 + 2*Day2 + 3*Day3 + 4*Day4 +
#             5*Day5 + 6*Day6 + 7*Day7 + 8*Day8 + 9*Day9
#
#       i ~~ start(550)*i
#       i ~ start(0)*1
#
#       s ~~ start(100)*s
#       s ~ start(0)*1
#
#       i ~~ start(40)*s
#
#       # fix intercepts
#       Day0 ~ 0*1
#       Day1 ~ 0*1
#       Day2 ~ 0*1
#       Day3 ~ 0*1
#       Day4 ~ 0*1
#       Day5 ~ 0*1
#       Day6 ~ 0*1
#       Day7 ~ 0*1
#       Day8 ~ 0*1
#       Day9 ~ 0*1
#
#       # apply equality constraints
#       Day0 ~~ v*Day0 + start(500)*Day0
#       Day1 ~~ v*Day1 + start(500)*Day1
#       Day2 ~~ v*Day2 + start(500)*Day2
#       Day3 ~~ v*Day3 + start(500)*Day3
#       Day4 ~~ v*Day4 + start(500)*Day4
#       Day5 ~~ v*Day5 + start(500)*Day5
#       Day6 ~~ v*Day6 + start(500)*Day6
#       Day7 ~~ v*Day7 + start(500)*Day7
#       Day8 ~~ v*Day8 + start(500)*Day8
#       Day9 ~~ v*Day9 + start(500)*Day9
#     "
#   }
#   if (rel == "0.5") {
#     mod <- "
#       # intercept with coefficients fixed to 1
#       i =~  1*Day0 + 1*Day1 + 1*Day2 + 1*Day3 + 1*Day4 +
#             1*Day5 + 1*Day6 + 1*Day7 + 1*Day8 + 1*Day9
#
#       # slope with coefficients fixed to 0:9 (number of days)
#       s =~  0*Day0 + 1*Day1 + 2*Day2 + 3*Day3 + 4*Day4 +
#             5*Day5 + 6*Day6 + 7*Day7 + 8*Day8 + 9*Day9
#
#       i ~~ start(275)*i
#       i ~ start(0)*1
#
#       s ~~ start(50)*s
#       s ~ start(0)*1
#
#       i ~~ start(20)*s
#
#       # fix intercepts
#       Day0 ~ 0*1
#       Day1 ~ 0*1
#       Day2 ~ 0*1
#       Day3 ~ 0*1
#       Day4 ~ 0*1
#       Day5 ~ 0*1
#       Day6 ~ 0*1
#       Day7 ~ 0*1
#       Day8 ~ 0*1
#       Day9 ~ 0*1
#
#       # apply equality constraints
#       Day0 ~~ v*Day0 + start(1300)*Day0
#       Day1 ~~ v*Day1 + start(1300)*Day1
#       Day2 ~~ v*Day2 + start(1300)*Day2
#       Day3 ~~ v*Day3 + start(1300)*Day3
#       Day4 ~~ v*Day4 + start(1300)*Day4
#       Day5 ~~ v*Day5 + start(1300)*Day5
#       Day6 ~~ v*Day6 + start(1300)*Day6
#       Day7 ~~ v*Day7 + start(1300)*Day7
#       Day8 ~~ v*Day8 + start(1300)*Day8
#       Day9 ~~ v*Day9 + start(1300)*Day9
#     "
#   }
#
#   mod
# }

#' @rdname true-values
#' @export
truth_growth <- function(rel, scale = 1) {
  if (rel == "0.8") {
    truth <- c(550, 0, 100, 0, 40, rep(500, 10))
  }
  if (rel == "0.5") {
    truth <- c(275, 0, 50, 0, 20, rep(1300, 10))
  }

  names(truth) <- c("i~~i", "i~1", "s~~s", "s~1", "i~~s", rep("v", 10))
  where_int <- grepl("i~1|s~1", names(truth))
  truth[where_int] <- truth[where_int] * scale
  truth[!where_int] <- truth[!where_int] * scale ^ 2

  truth
}

#' @rdname gen-data
#' @export
gen_data_growth <- function(
    n = 100,
    rel = 0.8,
    dist = "Normal",
    lavsim = FALSE,
    scale = 1,
    seed
  ) {
  dist <- match.arg(dist, c("Normal", "Kurtosis", "Non-normal"))
  if (isTRUE(lavsim)) {
    if (dist != "Normal")
      cli::cli_alert_warning("Forcing normal distribution with lavsim = TRUE.")
    dist <- "Normal_lav"
  }
  rel <- match.arg(as.character(rel), c("0.8", "0.5"))
  nobs <- n
  n.factors <- 2
  n.indicators <- 10
  mod <- txt_mod_growth_pop(rel = rel)

  # Population parameters ------------------------------------------------------
  if (rel == "0.8") {
    lambda <- matrix(data = c(rep(1, times = n.indicators), 0:(n.indicators-1)),
                     nrow = n.indicators,
                     ncol = n.factors)
    psi <- matrix(data = c(550, 40, 40, 100),
                  nrow = n.factors,
                  ncol = n.factors)
    theta <- matrix(data = 0,
                    nrow = n.indicators,
                    ncol = n.indicators)
    diag(theta) <- 500
  }
  if (rel == "0.5") {
    lambda <- matrix(data = c(rep(1, times = n.indicators), 0:(n.indicators-1)),
                     nrow = n.indicators,
                     ncol = n.factors)
    psi <- matrix(data = c(275, 20, 20, 50),
                  nrow = n.factors,
                  ncol = n.factors)
    theta <- matrix(data = 0,
                    nrow = n.indicators,
                    ncol = n.indicators)
    diag(theta) <- 1300
  }

  if (missing(seed)) seed <- NULL
  if (!is.null(seed)) set.seed(seed)

  # Simulate data --------------------------------------------------------------
  if (dist == "Normal_lav") {
    dat <- lavaan::simulateData(model = mod, sample.nobs = n)
  } else {
    if(dist == "Normal") {
      factors <- t(covsim::rIG(N = nobs,
                               sigma.target = psi,
                               skewness = rep(0, times = ncol(lambda)),
                               excesskurtosis = rep(0, times = ncol(lambda)),
                               reps = 1)[[1]])

      e <- t(covsim::rIG(N = nobs,
                         sigma.target = theta,
                         skewness = rep(0, times = nrow(theta)),
                         excesskurtosis = rep(0, times = nrow(theta)),
                         reps = 1)[[1]])
    } else if (dist == "Kurtosis") {
      factors <- t(covsim::rIG(N = nobs,
                               sigma.target = psi,
                               skewness = rep(0, times = ncol(lambda)),
                               excesskurtosis = rep(6, times = ncol(lambda)),
                               reps = 1)[[1]])

      e <- t(covsim::rIG(N = nobs,
                         sigma.target = theta,
                         skewness = rep(0, times = nrow(theta)),
                         excesskurtosis = rep(6, times = nrow(theta)),
                         reps = 1)[[1]])
    } else if (dist == "Non-normal") {
      factors <- t(covsim::rIG(N = nobs,
                               sigma.target = psi,
                               skewness = rep(-2, times = ncol(lambda)),
                               excesskurtosis = rep(6, times = ncol(lambda)),
                               reps = 1)[[1]])

      e <- t(covsim::rIG(N = nobs,
                         sigma.target = theta,
                         skewness = rep(-2, times = nrow(theta)),
                         excesskurtosis = rep(6, times = nrow(theta)),
                         reps = 1)[[1]])
    }

    dat <- as.data.frame(t(lambda %*% factors + e))
    colnames(dat) <- paste0("Day", 0:9)
  }

  dat <- dat * scale
  attr(dat, "truth") <- truth_growth(rel, scale = scale)
  attr(dat, "dist") <- dist
  dat
}

# Two-factor SEM models (model b) ----------------------------------------------
#' @rdname two-fac
#' @export
txt_mod_twofac_pop <- function(rel) {
  if (rel == "0.8") {
    # Reliabilities 0.80 -------------------------------------------------------
    mod <- "
    fx =~ 1*x1 + 0.7*x2 + 0.6*x3
    fy =~ 1*y1 + 0.7*y2 + 0.6*y3
    fy ~ 0.25*fx

    x1 ~~ 0.25*x1
    x2 ~~ 0.1225*x2
    x3 ~~ 0.09*x3

    y1 ~~ 0.25*y1
    y2 ~~ 0.1225*y2
    y3 ~~ 0.09*y3
    "
  }
  if (rel == "0.5") {
    # Reliabilities 0.50 -------------------------------------------------------
    mod <- "
    fx =~ 1*x1 + 0.7*x2 + 0.6*x3
    fy =~ 1*y1 + 0.7*y2 + 0.6*y3
    fy ~ 0.25*fx

    x1 ~~ 1*x1
    x2 ~~ 0.49*x2
    x3 ~~ 0.36*x3

    y1 ~~ 1*y1
    y2 ~~ 0.49*y2
    y3 ~~ 0.36*y3
    "
  }

  mod
}

#' @rdname two-fac
#' @export
txt_mod_twofac <- function(rel) {
  "
  fx =~ x1 + x2 + x3
  fy =~ y1 + y2 + y3
  fy ~ fx
  "
}

# txt_mod_twofac <- function(rel) {
#   rel <- match.arg(as.character(rel), c("0.8", "0.5"))
#
#   if (rel == "0.8") {
#     mod <- "
#       fx =~ x1 + start(0.7)*x2 + start(0.6)*x3
#       fy =~ y1 + start(0.7)*y2 + start(0.6)*y3
#
#       fx ~~ start(1)*fx
#       fy ~~ start(1)*fy
#       fy ~ start(0.25)*fx
#
#       x1 ~~ start(0.25)*x1
#       x2 ~~ start(0.1225)*x2
#       x3 ~~ start(0.09)*x3
#
#       y1 ~~ start(0.25)*y1
#       y2 ~~ start(0.1225)*y2
#       y3 ~~ start(0.09)*y3
#     "
#   }
#   if (rel == "0.5") {
#     mod <- "
#       fx =~ x1 + start(0.7)*x2 + start(0.6)*x3
#       fy =~ y1 + start(0.7)*y2 + start(0.6)*y3
#
#       fx ~~ start(1)*fx
#       fy ~~ start(1)*fy
#       fy ~ start(0.25)*fx
#
#       x1 ~~ start(1)*x1
#       x2 ~~ start(0.49)*x2
#       x3 ~~ start(0.36)*x3
#
#       y1 ~~ start(1)*y1
#       y2 ~~ start(0.49)*y2
#       y3 ~~ start(0.36)*y3
#     "
#   }
#
#   mod
# }

#' @rdname true-values
#' @export
truth_twofac <- function(rel, meanstructure = FALSE, scale = 1) {
  if (rel == "0.8") {
    truth <- c(0.7, 0.6, 0.7, 0.6, 0.25, rep(c(0.25, 0.1225, 0.09), 2), 1, 1)
  }
  if (rel == "0.5") {
    truth <- c(0.7, 0.6, 0.7, 0.6, 0.25, rep(c(1, 0.49, 0.36), 2), 1, 1)
  }

  names(truth) <- c(
    "fx=~x2", "fx=~x3", "fy=~y2", "fy=~y3",
    "fy~fx",
    "x1~~x1", "x2~~x2", "x3~~x3", "y1~~y1", "y2~~y2", "y3~~y3",
    "fx~~fx", "fy~~fy"
  )

  if (isTRUE(meanstructure)) {
    truth <- c(
      truth,
      c("x1~1" = 0, "x2~1" = 0, "x3~1" = 0, "y1~1" = 0, "y2~1" = 0, "y3~1" = 0)
    )
  }

  where_var <- grepl("~~", names(truth))
  truth[where_var] <- truth[where_var] * scale ^ 2
  # truth[!where_int] <- truth[!where_int] * scale ^ 2

  truth
}

#' @rdname gen-data
#' @export
gen_data_twofac <- function(
    n = 100,
    rel = 0.8,
    dist = "Normal",
    lavsim = FALSE,
    meanstructure = FALSE,
    scale = 1,
    seed
  ) {
  dist <- match.arg(dist, c("Normal", "Kurtosis", "Non-normal"))
  if (isTRUE(lavsim)) {
    if (dist != "Normal")
      cli::cli_alert_warning("Forcing normal distribution with lavsim = TRUE.")
    dist <- "Normal_lav"
  }
  rel <- match.arg(as.character(rel), c("0.8", "0.5"))
  nobs <- n
  n.factors <- 2
  n.indicators <- 6
  mod <- txt_mod_twofac_pop(rel = rel)

  # Population parameters ------------------------------------------------------

  # Create (empty) matrices
  lambda <- matrix(data = 0, nrow = n.indicators, ncol = n.factors)
  psi <- matrix(data = 0, nrow = n.factors, ncol = n.factors)
  beta <- matrix(data = 0, nrow = n.factors, ncol = n.factors)
  theta <- matrix(data = 0, nrow = n.indicators, ncol = n.indicators)
  eta <- matrix(data = NA, nrow = n.factors, ncol = nobs)
  e <- matrix(data = NA, nrow = n.indicators, ncol = nobs)

  # Define aspired reliability of indicators
  reliability <- matrix(data = 0, nrow = n.indicators, ncol = n.indicators)
  diag(reliability) <- as.numeric(rel)

  # Define factor loadings, factor variances and residual variances
  lambda[1:6, 1] <- c(1, 0.7, 0.6, 0, 0, 0)
  lambda[1:6, 2] <- c(0, 0, 0, 1, 0.7, 0.6)
  diag(psi) <- c(1, 1)
  beta[2, 1] <- 0.25
  diag(theta) <- diag((lambda %*% psi %*% t(lambda)) %*%
                        solve(reliability) - (lambda %*% psi %*% t(lambda)))

  if (missing(seed)) seed <- NULL
  if (!is.null(seed)) set.seed(seed)

  # Simulate data --------------------------------------------------------------
  if (dist == "Normal_lav") {
    dat <- lavaan::simulateData(model = mod, sample.nobs = n)
  } else {
    if(dist == "Normal") {
      random <- covsim::rIG(N = nobs,
                            sigma.target = psi,
                            skewness = rep(0, times = ncol(lambda)),
                            excesskurtosis = rep(0, times = ncol(lambda)),
                            reps = 1)[[1]]

      fx <- random[ , 1]
      fy <- fx*beta[2, 1] + random[ , 2]
      factors <- rbind(fx, fy)

      e <- t(covsim::rIG(N = nobs,
                         sigma.target = theta,
                         skewness = rep(0, times = nrow(theta)),
                         excesskurtosis = rep(0, times = nrow(theta)),
                         reps = 1)[[1]])
    }
    if (dist == "Kurtosis") {
      random <- covsim::rIG(N = nobs,
                            sigma.target = psi,
                            skewness = rep(0, times = ncol(lambda)),
                            excesskurtosis = rep(6, times = ncol(lambda)),
                            reps = 1)[[1]]

      fx <- random[ , 1]
      fy <- fx*beta[2, 1] + random[ , 2]
      factors <- rbind(fx, fy)

      e <- t(covsim::rIG(N = nobs,
                         sigma.target = theta,
                         skewness = rep(0, times = nrow(theta)),
                         excesskurtosis = rep(6, times = nrow(theta)),
                         reps = 1)[[1]])
    }
    if (dist == "Non-normal") {
      random <- covsim::rIG(N = nobs,
                            sigma.target = psi,
                            skewness = rep(-2, times = ncol(lambda)),
                            excesskurtosis = rep(6, times = ncol(lambda)),
                            reps = 1)[[1]]

      fx <- random[ , 1]
      fy <- fx*beta[2, 1] + random[ , 2]
      factors <- rbind(fx, fy)

      e <- t(covsim::rIG(N = nobs,
                         sigma.target = theta,
                         skewness = rep(-2, times = nrow(theta)),
                         excesskurtosis = rep(6, times = nrow(theta)),
                         reps = 1)[[1]])
    }

    dat <- as.data.frame(t(lambda %*% factors + e))
    colnames(dat) <- c("x1", "x2", "x3", "y1", "y2", "y3")
  }

  dat <- dat * scale
  attr(dat, "truth") <- truth_twofac(rel, meanstructure, scale)
  attr(dat, "dist") <- dist
  dat
}

#' @rdname true-values
#' @param x A data frame generated by [gen_data_growth()] or
#'   [gen_data_twofac()].
#' @export
truth <- function(x) attr(x, "truth")
